### ISSUE TITLE
Mutable states 

### ISSUE THREAD

**Issue by yatharthmathur** [ARgorithm/Toolkit#12]
Possible argument in methods to disable states to prevent unnecessary states being added.
Eg : Not storing states of Array declare whenever `arr[i][j]` is used. We can just pass in an argument in the function call there to mute the state storage.

**Comment by alanpjohn** [comment]
We could also add a feature for deleting variables which would be useful in preventing overcrowding when rendering
for example we can add a `delete_state` , whatever variable gets mentioned in delete state will be chucked out of the render.

> I might use a temp variable which i dont need to keep rendered so i can delete them and maintain focus on the more important parts of the program.

If we add mutable states feature with variable deletion state , I think they will be more than enough to handle unnecessary states as well control variable persistance during rendering

**Comment by alanpjohn** [comment]
As we had discussed on discord, states will be muted during the rendering process. This issue will be taken care of in [client application](https://github.com/ARgorithm/Unity-App)
