### ISSUE TITLE
schema for .config,json

### ISSUE THREAD

**Issue by alanpjohn** [ARgorithm/Toolkit#23]
With every argorithm, we are asking the programmer to provide a .config.json file for metadata regarding function input. For example lets take the `fibonacci.config.json`
```json
{
    "argorithmID": "fibonacci", 
    "file": "fibonacci.py", 
    "function": "run", 
    "parameters": {
        "n" : "int"
    }, 
    "default": {
        "n" : 4
    }, 
    "description": "Print the nth fibonacci number"
}
```
Here in parameters we ask the user to tell us about parameters that he expects for his file which is as we see `n` which is an int.
some users might write integer or INT. which should be a problem but isnt as we are never parsing this information.

If we attach a proper schema on the terms that you can used to classify your variable, this might help in #3 and also help in adding a user input option when [testing argorithm using CLI](https://github.com/ARgorithm/toolkit/blob/49e08454d8f179d46f3c819cc219de0006a387eb/ARgorithmToolkit/cli.py#L451).

**Comment by alanpjohn** [comment]
we can use a similar mechanism that we are using for `.design.yml` files to ensure that the values used in describing the parameters are upto our expectations but in this case we will need to change the extension from `.config,json` as JSONSchema for this extension already exists and it could prove troublesome for programmers. maybe we can change the extension to `.argorithm.json`

@yatharthmathur any other ideas?

**Comment by yatharthmathur** [comment]
Can we use the initial parsing of the submitted argorithm to automate the creation of metadata?

**Comment by alanpjohn** [comment]
Closing this issue as this as per our discussion is a part of #3
