### ISSUE TITLE
Optimization for state

### ISSUE THREAD

**Issue by yatharthmathur** [ARgorithm/Toolkit#25]
As discussed in the excel sheet with @TheForeverLost (upload it here as well). We need a way to log the previous values of modified data in the StateSet so that it can be used to undo the values in the Unity side of things to avoid the dramatic increase in StateLog object. (can be done by just added one prev_val field in the assign types state set or something more generic if possible).

**Comment by alanpjohn** [comment]
Added details required [here](https://github.com/ARgorithm/Unity-App/issues/5)
