### ISSUE TITLE
Implementing Map/Dict functionality with ARgorithmToolkit objects.

### ISSUE THREAD

**Issue by yatharthmathur** [ARgorithm/Toolkit#27]
To implement a lot of algorithms, a dict or hashmap maybe a necessary Data-structure. It'll require some form of generics or interface classes to use as key-value pairs, to ensure that the correct data is being written into the states, and object references aren't lost.

**Comment by alanpjohn** [comment]
# class serializability and storing object id in state

- within `state_def`
make object id a compulsory part of metadata

- all ARgorithmToolkit classes to be made JSON serialisable.
refer [this](https://stackoverflow.com/questions/3768895/how-to-make-a-class-json-serializable) for more info
We can do this easily by creating our own `ARgorithmToolkit.utils.Encoder` which can parse StateSet into a JSON and convert ARgorithmToolkit class objects into strings/objects containing reference to the id of the ARgorithmToolkit object used in body

lets say a `ARgorithmToolkit.Array` can be serialised into a string like 
```Json
"$argorithm_array_{id}"
``` 
or into an object like
```json
{
     "argorithm_object" : {
           "type" : "Array",
           "id" : "<whatever id>"
     }
}
```

**Comment by alanpjohn** [comment]
Right now object deletion is only recorded in linkedlist
Should we also implement delete states in all other data structures as well 
```python
arr = ARgorithmToolkit.Array(name='arr',algo=algo,data=[1,2,3])
arr = ARgorithmToolkit.Array(name='arr',algo=algo,data=[4,5,7])
```
as these objects are overwritten in python, shouldnt that happen in application as well and we might need a delete state to do that

**Comment by yatharthmathur** [comment]
They're not technically over written, they remain in memory the reference counter to that object is decremented. If that reference counter reaches 0, it is collected by Garbage collector

**Comment by alanpjohn** [comment]
> They're not technically over written, they remain in memory the reference counter to that object is decremented. If that reference counter reaches 0, it is collected by Garbage collector

yeah what i meant was by overwritten is that they are no longer accessed by any variable
so thats a yes or a no on the `_del` states?
