### ISSUE TITLE
CLI bug on Submit for Arrays

### ISSUE THREAD

**Issue by yatharthmathur** [ARgorithm/Toolkit#31]
Submitting Array based ARgorithms are leading to TESTING FAILED errors, or APPLICATION ERROR (on server side)
```python
import ARgorithmToolkit

def run(**kwargs):
    algo = ARgorithmToolkit.StateSet()
    arr1 = ARgorithmToolkit.Array(name='arr1', data=[1,2,3], algo=algo)
    arr2 = ARgorithmToolkit.Array(name='arr2', data=[2,5], algo=algo)
    arr1.compare(0,1)
    arr2.swap(0,1)
    return algo
```
Also resubmitting results in TEST PASSED and file on server changes with the failed tests.
This leads to random behaviour.

![123](https://user-images.githubusercontent.com/31852880/109278732-e4fca480-783e-11eb-85f4-a132cbdf70c7.PNG)

@TheForeverLost submitted the same file and got it to work.
POSSIBLE EXPLANATION : Account privileges.

Also, Array assignment doesn't work because of np.integer type being Unserializable. Changes in Toolkit.Array required.

**Comment by yatharthmathur** [comment]
I relogged in as a new account and it worked

**Comment by alanpjohn** [comment]
- [x] fixing numpy types serialisability by expanding `encoder` or altering `ARgorithmToolkit.Array`
https://stackoverflow.com/questions/50916422/python-typeerror-object-of-type-int64-is-not-json-serializable

- [x] Test File reader and configure functionalities dealing with file testing

**Comment by alanpjohn** [comment]
@yatharthmathur 
try installing the testpypi version of toolkit and test if it works better for you
```bash
$ pip install -i https://test.pypi.org/simple/ ARgorithmToolkit==0.2.0
```
