### ISSUE TITLE
Comment behavior optimization

### ISSUE THREAD

**Issue by yatharthmathur** [ARgorithm/Toolkit#34]
Currently all the get and set methods in arrays, vectors and other classes aren't indicating the user of any type of data about the datastructure the operation is being performed on.  There is no default comment for get method in arrays and vectors anyways, so that needs to be added along with the name of the variable the operation is being performed on.
eg: 
This should be a comment that is to be added by default to all get and set methods for arrays
Get : 
```python
f"Reading index {i} from array : {name}"
```

Set:
```python
f"Writing value {value} at index {i} in array : {name}"
```

**Comment by alanpjohn** [comment]
Closing issue as repo is being archived.
