### ISSUE TITLE
Tags and various other search parameters for each ARgorithm in the database

### ISSUE THREAD

**Issue by yatharthmathur** [ARgorithm/Toolkit#35]
Users should be able to search various ARgorithms and hence they need to be tagged and have various metadeta for users to easily search or identify them using multiple filters.

We can have a tag field for the basic use where each tag will store the topic of the ARgorithm the user has submitted and at Application End the data can easily be filtered to best suit the search parameters.

Changes in ARgorithm CLI and Config.json files are required.

**Comment by alanpjohn** [comment]
Closing issue as repo is being archived.
